"""
Generate config/genesis_lexicon.json from the hardcoded keyword taxonomy.
Run: python scripts/generate_lexicon.py
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).parent.parent

# ---------------------------------------------------------------------------
# Keyword data — extracted from KiteAI_Baseline_Keywords_Matrix.pdf
# ---------------------------------------------------------------------------

CLASS_A_KEYWORDS = [
    "10x cheaper inference",
    "Aider latency",
    "API bill shock",
    "API got slower overnight",
    "API timeout errors",
    "Anthropic API down",
    "Anthropic API timeout",
    "Anthropic rate limit",
    "Aphrodite engine",
    "AWQ vs GPTQ",
    "B200 cost",
    "B200 inference",
    "B200 vs H200",
    "batch API delays",
    "burning through credits",
    "Claude 3.7 Sonnet",
    "Claude API expensive",
    "Claude Code rate limit",
    "Claude Code slow",
    "Claude Haiku 4.5 latency",
    "Claude Opus 4.6 cost",
    "Claude Opus 4.7 cost",
    "Claude Opus 4.7 latency",
    "Claude Opus 4.7 outage",
    "Claude Opus 4.7 rate limit",
    "Claude Opus 4.7 slow",
    "Claude Sonnet 4.5 slow",
    "Claude Sonnet 4.6 cost",
    "Claude Sonnet 4.6 latency",
    "Claude Sonnet 4.6 slow",
    "Cerebras WSE-3 inference",
    "Codex API cost",
    "Codex CLI slow",
    "Cohere API latency",
    "Command R+ cost",
    "context window not enough",
    "Cursor Composer",
    "Cursor agent",
    "Cursor expensive",
    "Cursor latency",
    "Cursor slow",
    "DeepSeek R1 reasoning",
    "DeepSeek R1 self-hosted",
    "DeepSeek V3 cost",
    "DeepSeek V3 latency",
    "Devin AI cost",
    "EAGLE speculative",
    "FP8 inference",
    "fine-tuning Llama 4",
    "fine-tuning Qwen 3",
    "first token taking forever",
    "function calling broken",
    "GGUF quantization quality",
    "GPT-4o deprecated",
    "GPT-4o still better",
    "GPT-5 expensive",
    "GPT-5.2 latency",
    "GPT-5.3-Codex slow",
    "GPT-5.4 cost",
    "GPT-5.4 latency",
    "GPT-5.4 mini cost",
    "GPT-5.4 nano latency",
    "GPT-5.5 Codex",
    "GPT-5.5 TTFT",
    "GPT-5.5 Thinking latency",
    "GPT-5.5 Instant latency",
    "GPT-5.5 context window",
    "GPT-5.5 cost",
    "GPT-5.5 expensive",
    "GPT-5.5 hallucination",
    "GPT-5.5 latency",
    "GPT-5.5 outage",
    "GPT-5.5 Pro slow",
    "GPT-5.5 rate limit",
    "GPT-5.5 slow",
    "GPT-5.5 timeout",
    "Gemini 2.5 Pro still",
    "Gemini 3 Deep Think slow",
    "Gemini 3 Flash slow",
    "Gemini 3.1 Flash-Lite latency",
    "Gemini 3.1 Pro cost",
    "Gemini 3.1 Pro latency",
    "Gemini 3.1 Pro slow",
    "Gemini 3.1 Pro thinking",
    "Gemini 3.5 Flash cost",
    "Gemini 3.5 Flash latency",
    "Gemini API outage",
    "Gemini Live cost",
    "Gemini Live voice latency",
    "GitHub Copilot latency",
    "Google AI Studio slow",
    "Google TPU v5p",
    "Google TPU v6",
    "Groq LPU latency",
    "Grok 3 cost",
    "Grok 4 API",
    "Grok 4 cost",
    "Grok 4 latency",
    "H100 inference cost",
    "H200 availability",
    "INT4 quality loss",
    "JSON mode broken",
    "LMDeploy latency",
    "LoRA inference overhead",
    "Llama 3.1 405B cost",
    "Llama 3.3 70B latency",
    "Llama 4 Behemoth",
    "Llama 4 Maverick cost",
    "Llama 4 Scout inference",
    "Llama TensorRT-LLM",
    "Llama fine-tuning cost",
    "Medusa decoding",
    "MI300X performance",
    "MI355X",
    "Mistral Large latency",
    "Mistral Medium 3 cost",
    "Mixtral 8x22B inference",
    "NVIDIA Blackwell shortage",
    "Nvidia GB200",
    "Ollama context",
    "Ollama slow",
    "OpenAI reasoning delay",
    "Perplexity API rate limit",
    "Perplexity Comet hallucination",
    "Perplexity Comet latency",
    "Perplexity Comet slow",
    "Perplexity Deep Research slow",
    "Perplexity Personal Computer",
    "Perplexity Pro cost",
    "Perplexity Sonar API",
    "Phi-4 latency",
    "Qwen 2.5 cost",
    "Qwen 3 inference",
    "Qwen Coder latency",
    "TTFT regression",
    "TGI vs vLLM",
    "TensorRT-LLM build",
    "TensorRT-LLM speedup",
    "Tenstorrent inference",
    "Vertex AI latency",
    "Windsurf latency",
    "AWS Trainium 2",
    "SGLang structured output",
    "SGLang vs vLLM",
    "Yi-Large cost",
    "API bill shock",
    "api got slower overnight",
    "batch API delays",
    "edge inference deployment",
    "inference cost is killing us",
    "llama.cpp performance",
    "long context degradation",
    "model deprecated breaking us",
    "model degraded",
    "model ignoring system prompt",
    "model returning XML",
    "moved off GPT-4o",
    "moved off OpenAI",
    "needle in haystack fail",
    "o3 cost",
    "o3 latency",
    "o3-mini latency",
    "o4-mini cost",
    "open source caught up",
    "open source is better now",
    "production LLM latency",
    "prompt caching broken",
    "prompt caching savings",
    "quantization quality loss",
    "rate limited again",
    "scaling LLM in production",
    "self-hosting Llama cost",
    "self-hosting Llama production",
    "speculative decoding speedup",
    "structured output broken",
    "switched from Claude to GPT",
    "switched from GPT to Claude",
    "tokens per second dropped",
    "tool calling failed",
    "vLLM 0.6",
    "vLLM latency",
    "vLLM throughput",
    "xAI API rate limit",
]
# Deduplicate
CLASS_A_KEYWORDS = sorted(set(CLASS_A_KEYWORDS))

CLASS_B_KEYWORDS = sorted(set([
    "Activepieces AI",
    "AI gateway latency",
    "Anthropic MCP",
    "AutoGen role confusion",
    "AutoGen stuck",
    "AutoGen v0.4",
    "Arize Phoenix",
    "Bubble AI workflow",
    "Chroma performance",
    "Cohere rerank cost",
    "CrewAI agent loop",
    "CrewAI handoff failed",
    "CrewAI hierarchical",
    "CrewAI infinite loop",
    "DSPy MIPRO",
    "DSPy compilation slow",
    "DSPy optimizer",
    "GraphRAG slow",
    "Helicone tracing",
    "Inngest AI workflow",
    "LanceDB latency",
    "LangChain JSON parse",
    "LangChain abstraction hell",
    "LangChain replaced with",
    "LangChain slow",
    "LangChain timeout",
    "LangChain tool calling broken",
    "LangGraph checkpointer slow",
    "LangGraph cycle",
    "LangGraph latency",
    "LangGraph state bug",
    "LangServe deployment",
    "LangSmith expensive",
    "LangSmith trace",
    "LiteLLM proxy",
    "LlamaIndex RAG slow",
    "LlamaIndex Workflows",
    "LlamaIndex retrieval latency",
    "LlamaIndex routing",
    "Langfuse trace",
    "MCP Atlas benchmark",
    "MCP client",
    "MCP integration",
    "MCP server broken",
    "MCP server slow",
    "MCP tool timeout",
    "MCP vs function calling",
    "Make.com OpenAI module",
    "Mastra agent",
    "Microsoft GraphRAG",
    "Milvus latency",
    "MongoDB Atlas Vector",
    "OpenAI Agents SDK",
    "OpenAI Assistants deprecated",
    "OpenAI Swarm replaced",
    "OpenRouter cost",
    "OpenRouter latency",
    "Pinecone expensive",
    "Pinecone latency",
    "Pinecone query slow",
    "Pinecone serverless",
    "Phoenix observability",
    "Portkey gateway",
    "Pydantic AI agent",
    "Qdrant hybrid search",
    "Qdrant timeout",
    "RAG accuracy drop",
    "RAG chunking strategy",
    "RAG eval failing",
    "RAG hallucination",
    "RAG retrieval slow",
    "RAG vs long context",
    "Semantic Kernel handoff",
    "Semantic Kernel slow",
    "Turbopuffer cost",
    "Weaviate slow",
    "Weaviate v1.27",
    "Zapier AI step failed",
    "Zapier Central agent",
    "agent benchmarking",
    "agent burning tokens",
    "agent debugging hell",
    "agent eval",
    "agent gave up",
    "agent hallucinating tool",
    "agent ignored tool",
    "agent infinite recursion",
    "agent observability",
    "agent stuck in loop",
    "agentic RAG",
    "contextual retrieval",
    "embedding latency",
    "hybrid search latency",
    "llm as judge unreliable",
    "moved off LangChain",
    "multi-agent coordination broken",
    "n8n AI node timeout",
    "n8n OpenAI failed",
    "n8n agent node",
    "pgvector slow",
    "pgvector vs Pinecone",
    "reranker slow",
]))

CLASS_C_KEYWORDS = sorted(set([
    "8khz audio STT",
    "Agora voice AI",
    "Air AI latency",
    "Air AI pricing",
    "AssemblyAI Universal-2",
    "AssemblyAI latency",
    "AssemblyAI pricing",
    "AssemblyAI streaming",
    "Bandwidth voice",
    "Bland AI alternative",
    "Bland AI down",
    "Bland AI hallucination",
    "Bland AI latency",
    "Bland AI outage",
    "Bland AI pricing",
    "Bland AI quality",
    "Cartesia Sonic",
    "Cartesia latency",
    "Cartesia pricing",
    "Cartesia streaming",
    "ChatGPT voice mode",
    "Coval voice testing",
    "Daily prebuilt voice",
    "Daily.co Pipecat",
    "Daily.co latency",
    "Deepgram Aura TTS",
    "Deepgram Nova 3",
    "Deepgram accuracy",
    "Deepgram alternative",
    "Deepgram latency",
    "Deepgram pricing",
    "Deepgram streaming",
    "Distil-Whisper latency",
    "ElevenLabs Flash",
    "ElevenLabs Turbo",
    "ElevenLabs alternative",
    "ElevenLabs latency",
    "ElevenLabs pricing",
    "ElevenLabs rate limit",
    "ElevenLabs streaming",
    "ElevenLabs v3",
    "ElevenLabs voice clone",
    "GPT Realtime 1.5",
    "GPT-4o Realtime voice",
    "GPT-5 voice mode",
    "Gladia STT",
    "Hamming AI testing",
    "Hume EVI",
    "Hume Octave",
    "Janus WebRTC",
    "LiveKit Agents",
    "LiveKit Cloud",
    "LiveKit latency",
    "LiveKit pricing",
    "Mediasoup",
    "OpenAI Realtime API",
    "OpenAI Realtime cost",
    "OpenAI Realtime latency",
    "OpenAI TTS latency",
    "Parakeet RNNT",
    "Pipecat Daily",
    "Pipecat latency",
    "Pipecat pipeline",
    "Pipecat slow",
    "PlayDialog",
    "PlayHT latency",
    "PlayHT pricing",
    "Plivo cost",
    "Plivo voice AI",
    "Rev AI latency",
    "Retell SDK",
    "Retell alternative",
    "Retell barge-in",
    "Retell crashed",
    "Retell down",
    "Retell error",
    "Retell expensive",
    "Retell latency",
    "Retell outage",
    "Retell pricing",
    "Retell timeout",
    "Retell to Vapi",
    "Retell webhook",
    "Rime AI latency",
    "Rime Arcana",
    "Rime pricing",
    "SIP trunk voice AI",
    "STT-LLM-TTS pipeline",
    "STT mishearing accent",
    "Sesame Maya",
    "Sesame voice",
    "SignalWire voice",
    "Soniox STT",
    "Speechmatics latency",
    "Speechmatics multilingual",
    "Synthflow alternative",
    "Synthflow latency",
    "Synthflow pricing",
    "TTFB voice agent",
    "Telnyx cost",
    "Telnyx voice AI",
    "Telnyx vs Twilio voice",
    "Twilio ConversationRelay",
    "Twilio Media Streams",
    "Twilio cost",
    "Twilio expensive",
    "Twilio voice latency",
    "Twilio webhook timeout",
    "Ultravox alternative",
    "Ultravox latency",
    "Ultravox open source",
    "Ultravox pricing",
    "VAD missing speech",
    "VAD too sensitive",
    "Vapi alternative",
    "Vapi barge-in",
    "Vapi billing",
    "Vapi crashed",
    "Vapi down",
    "Vapi endpointing",
    "Vapi error",
    "Vapi expensive",
    "Vapi latency",
    "Vapi outage",
    "Vapi pricing",
    "Vapi rate limit",
    "Vapi support",
    "Vapi timeout",
    "Vapi to Retell",
    "Vapi turn detection",
    "Vapi vs Bland",
    "Vapi vs Retell",
    "Vapi webhook",
    "VoxImplant",
    "WebRTC voice latency",
    "WhisperX latency",
    "Whisper accented",
    "Whisper hallucination",
    "Whisper latency",
    "Whisper v3 Turbo",
    "agent interrupting me",
    "audio cutting out voice",
    "audio dropouts voice",
    "barge-in not working",
    "built a voice receptionist",
    "custom voice stack",
    "end-to-end voice model",
    "endpointing too aggressive",
    "endpointing too slow",
    "faster-whisper",
    "launched my voice AI",
    "latency budget voice",
    "latency decomposition voice",
    "monolithic voice model",
    "moved off Retell",
    "moved off Vapi",
    "narrow-band audio voice AI",
    "open source voice agent",
    "p99 voice latency",
    "phone audio quality",
    "real-time voice latency",
    "self-hosted voice agent",
    "shipped a voice agent",
    "stacked latency voice",
    "stitched voice pipeline",
    "sub-second voice agent",
    "voice AI MVP",
    "voice AI demo failed",
    "voice AI feels slow",
    "voice AI for clients",
    "voice AI not production ready",
    "voice agent TTFT",
    "voice agent context window",
    "voice agent crashed",
    "voice agent dropped call",
    "voice agent echo",
    "voice agent feels laggy",
    "voice agent forgot",
    "voice agent hallucinated",
    "voice agent in production",
    "voice agent jitter",
    "voice agent lost context",
    "voice agent never stops talking",
    "voice agent p95",
    "voice agent restarted",
    "voice agent robotic pause",
    "voice agent silence detection",
    "voice agent talking over user",
    "voice agent took 3 seconds",
    "voice agent took 4 seconds",
    "voice bot awkward pause",
    "voice bot feels broken",
    "voice bot misheard",
    "voice bot stuttering",
    "voice latency 2 seconds",
    "voice mode latency",
    "voice pipeline latency",
    "voice webhook failed",
    "white-label voice agent",
]))

CLASS_D_KEYWORDS = sorted(set([
    "10x cheaper inference",
    "AAA agency revenue",
    "AI agency MRR",
    "AI agency profitable",
    "AI burn rate",
    "AI burning cash",
    "AI commodity pricing",
    "AI markup",
    "AI pass-through cost",
    "AI profitability",
    "AI startup unit economics",
    "Anyscale cost",
    "API costs scaling",
    "B200 hourly cost",
    "BPO voice AI cost",
    "Cartesia pricing model",
    "Claude vs GPT cost",
    "CoreWeave cost",
    "Deepgram vs Whisper cost",
    "ElevenLabs cost per character",
    "Fireworks AI cost",
    "GPU autoscaling cost",
    "GPU cost inference",
    "Gemini cost comparison",
    "GPT-5.5 cost analysis",
    "H100 hourly cost",
    "H200 hourly cost",
    "Lambda Labs GPU",
    "LLM cost optimization",
    "LLM cost per call",
    "LLM inference cost",
    "LLM token cost",
    "Modal pricing",
    "Replicate cost",
    "RunPod cost",
    "STT cost per minute",
    "Series A burn AI",
    "TTS bill shock",
    "TTS cost per character",
    "Together AI cost",
    "Whisper self-hosted cost",
    "AI labor displacement",
    "batch API discount",
    "cheaper than Claude Opus",
    "cheaper than GPT-5.5",
    "cheaper than Gemini 3.1 Pro",
    "cold start cost",
    "compute cost startup",
    "cost per call AI",
    "fraction of the cost",
    "free tier abuse",
    "inference per second cost",
    "inference per token cost",
    "open source voice cheaper",
    "outcome-based AI pricing",
    "per-org rate limit",
    "prompt caching savings",
    "prompt compression",
    "rate limit by user",
    "scaling AI costs",
    "seat-based AI pricing",
    "self-host break even",
    "self-hosted Llama math",
    "self-hosting cheaper than",
    "spot GPU inference",
    "usage-based pricing AI",
    "voice AI ARR",
    "voice AI CAC",
    "voice AI LTV",
    "voice AI bill shock",
    "voice AI break even",
    "voice AI gross margin",
    "voice AI margin",
    "voice AI per minute cost",
    "voice AI profitable",
    "voice AI unit economics",
    "voice AI volume discount",
    "voice AI MRR",
    "voice agency margins",
    "voice agent ROI",
    "voice API hidden fees",
    "voice infra cost",
    "voice reseller margin",
    "white-label voice cost",
]))

CLASS_E_KEYWORDS = sorted(set([
    "AI4Bharat",
    "Afrikaans STT",
    "African accent STT",
    "African languages voice",
    "Allam Saudi LLM",
    "Amharic STT",
    "Amharic TTS",
    "Arabic ASR",
    "Arabic AI caller",
    "Arabic LLM open source",
    "Arabic STT",
    "Arabic TTS",
    "Arabic chatbot",
    "Arabic speech recognition",
    "Arabic voice AI",
    "Arabic voice agent",
    "Arabic voice bot",
    "AssemblyAI Arabic",
    "Assamese STT",
    "Bahasa Indonesia STT",
    "Bahasa Indonesia TTS",
    "Bahasa Indonesia voice",
    "Bahasa Malaysia voice",
    "Bengali STT",
    "Bengali TTS",
    "Bengali voice AI",
    "Bangla voice",
    "Bhasha voice AI",
    "Bhashini",
    "Burmese STT",
    "Burmese voice AI",
    "Cantonese STT",
    "Cantonese voice AI",
    "Cartesia Arabic",
    "Catalan voice",
    "Darija STT",
    "Darija voice AI",
    "Deepgram Arabic",
    "Egyptian Arabic STT",
    "Egyptian Arabic TTS",
    "Egyptian voice AI",
    "ElevenLabs Arabic",
    "Farsi STT",
    "Farsi voice AI",
    "Dari voice",
    "Filipino STT",
    "Filipino voice AI",
    "Greek voice AI",
    "Gulf Arabic STT",
    "Gulf Arabic TTS",
    "Gujarati STT",
    "Gujarati voice AI",
    "Hausa STT",
    "Hausa voice AI",
    "Hebrew STT",
    "Hebrew voice AI",
    "Hindi AI caller",
    "Hindi STT",
    "Hindi TTS",
    "Hindi voice AI",
    "Hindi voice agent",
    "Hinglish STT",
    "Hinglish TTS",
    "Hinglish code-switching",
    "Hinglish voice",
    "Igbo STT",
    "Igbo voice AI",
    "Indian English STT",
    "Indian English TTS",
    "Indian accent voice AI",
    "IndicConformer",
    "IndicTrans",
    "Indic STT",
    "Indic TTS",
    "Iraqi Arabic STT",
    "Jais Arabic LLM",
    "Jordanian Arabic",
    "Kannada STT",
    "Kannada TTS",
    "Kannada voice AI",
    "Kazakh voice",
    "Khaleeji STT",
    "Khaleeji voice",
    "Khmer STT",
    "Khmer voice",
    "Kiswahili voice",
    "Konkani voice",
    "Lao voice AI",
    "Levantine Arabic voice",
    "Levantine STT",
    "MSA TTS",
    "MSA vs dialect Arabic",
    "Malay STT",
    "Malay TTS",
    "Malayalam STT",
    "Malayalam TTS",
    "Malayalam voice AI",
    "Mandarin code-switching",
    "Marathi STT",
    "Marathi TTS",
    "Marathi voice AI",
    "Odia voice AI",
    "Persian TTS",
    "Pashto voice AI",
    "Punjabi STT",
    "Punjabi voice AI",
    "Romanian voice",
    "Sarvam Bulbul",
    "Sarvam Saaras",
    "Sarvam voice",
    "Sudanese Arabic",
    "Swahili STT",
    "Swahili TTS",
    "Swahili voice AI",
    "Taglish STT",
    "Taglish code-switching",
    "Tagalog STT",
    "Tagalog voice AI",
    "Tamil STT",
    "Tamil TTS",
    "Tamil code-switching",
    "Tamil voice AI",
    "Telugu STT",
    "Telugu TTS",
    "Telugu voice AI",
    "Thai STT",
    "Thai TTS",
    "Thai tones",
    "Thai voice AI",
    "Turkish STT",
    "Turkish voice AI",
    "Urdu STT",
    "Urdu TTS",
    "Urdu voice AI",
    "Uzbek voice AI",
    "Vietnamese STT",
    "Vietnamese TTS",
    "Vietnamese tones STT",
    "Vietnamese voice AI",
    "Whisper Arabic",
    "Whisper Egyptian",
    "Whisper Gulf Arabic",
    "Whisper Levantine",
    "Whisper accented fail",
    "Whisper hallucination Arabic",
    "Whisper hallucination Hindi",
    "Xhosa STT",
    "Yemeni Arabic",
    "Yoruba STT",
    "Yoruba voice AI",
    "Zulu voice AI",
    "accent detection failure",
    "auto language detection voice",
    "code-mixing Hindi",
    "code-mixing voice AI",
    "code-switch latency",
    "code-switching Hindi English",
    "code-switching STT",
    "global voice AI",
    "language identification STT",
    "localized voice AI",
    "low-resource TTS",
    "low-resource language STT",
    "monolithic multilingual TTS",
    "multilingual barge-in",
    "multilingual voice agent",
    "noisy audio dialect STT",
    "non-English speech recognition",
    "non-English speech synthesis",
    "non-English voice AI",
    "phone audio non-English",
    "regional dialect voice",
    "stitched multilingual model",
    "STT mishearing accent",
    "TTS accent unnatural",
    "voice AI Bahrain",
    "voice AI Dubai",
    "voice AI Kuwait",
    "voice AI MENA",
    "voice AI Oman",
    "voice AI Qatar",
    "voice AI Riyadh",
    "voice AI Saudi",
    "voice AI UAE",
    "voice AI translation",
    "voice agent multilingual",
    "voice clone non-English",
]))

CLASS_F_KEYWORDS = sorted(set([
    "AAA agency",
    "AI BDR voice",
    "AI SDR voice",
    "AI agency build",
    "AI agency client",
    "AI agency package",
    "AI agency retainer",
    "AI appointment setter voice",
    "AI automation agency",
    "AI cold caller",
    "AI interviewer voice",
    "BPO voice AI",
    "GHL voice AI",
    "GoHighLevel voice",
    "HubSpot voice AI",
    "HVAC AI booking",
    "HVAC AI receptionist",
    "HVAC voice agent",
    "auto dealer AI caller",
    "auto dealer voice agent",
    "built a voice AI agency",
    "building a voice AI agency",
    "call center AI deployment",
    "client billing voice agent",
    "dental AI front desk",
    "dental AI receptionist",
    "dental voice agent",
    "education AI tutor voice",
    "first voice AI client",
    "fitness studio AI",
    "gym AI receptionist",
    "healthcare AI receptionist",
    "healthcare voice agent",
    "home services AI caller",
    "home services voice agent",
    "hospitality voice AI",
    "hotel AI receptionist",
    "hotel voice agent",
    "inbound AI receptionist production",
    "insurance AI agent",
    "insurance voice bot",
    "legal AI intake",
    "legal AI receptionist",
    "medical AI scheduling",
    "multi-tenant voice AI",
    "no-code AI agency",
    "onboarded voice AI client",
    "outbound AI caller production",
    "plumbing AI dispatch",
    "plumbing AI receptionist",
    "real estate AI SDR",
    "real estate AI caller",
    "real estate voice bot",
    "recruiting AI screener",
    "reselling voice AI",
    "restaurant AI phone",
    "restaurant AI reservations",
    "salon AI receptionist",
    "scaling voice AI agency",
    "selling voice AI",
    "shipped voice agent client",
    "spa AI booking",
    "starting a voice AI agency",
    "sub-accounts voice API",
    "tutoring voice AI",
    "veterinary AI receptionist",
    "vet voice agent",
    "voice AI ARR",
    "voice AI consultant",
    "voice AI demo to client",
    "voice AI freelancer",
    "voice AI MRR",
    "voice AI agency niche",
    "voice AI agency results",
    "voice AI proposal",
    "voice agency MRR",
    "voice agency revenue",
    "voice agent CRM integration",
    "voice agent CRM sync",
    "voice agent calendar",
    "white-label Retell",
    "white-label Vapi",
]))

CLASS_G_KEYWORDS = sorted(set([
    "1M token context",
    "10M token context",
    "AI agents",
    "AI alignment",
    "AI consciousness",
    "AI deployment policy",
    "AI governance",
    "AI labor displacement",
    "AI regulation EU AI Act",
    "AI rights",
    "AI safety",
    "AI takeover risk",
    "AI winter",
    "AGI by 2027",
    "AGI by 2030",
    "AGI timeline",
    "ASI",
    "ALBERT",
    "Adam optimizer",
    "AlexNet",
    "AlphaGo",
    "AlphaZero",
    "Anthropic constitutional",
    "Anthropic interpretability",
    "attention is all you need",
    "autoencoder",
    "BERT",
    "BERT masked language",
    "Bayesian networks",
    "Deep Blue chess",
    "DeepMind Atari",
    "DeepMind Chinchilla",
    "DPO",
    "DALL-E",
    "Dartmouth Conference",
    "Direct Preference Optimization",
    "ELIZA chatbot",
    "ELIZA effect",
    "Elman network",
    "FlashAttention",
    "FlashAttention-3",
    "GANs",
    "GOFAI",
    "GPT-2",
    "GPT-3",
    "GPT-3 emergent",
    "GQA grouped query attention",
    "GRU",
    "Genie world model",
    "Good Old-Fashioned AI",
    "Goodfellow GAN",
    "GloVe embeddings",
    "Hidden Markov Models",
    "HMM speech recognition",
    "Hinton deep belief networks",
    "Hochreiter LSTM",
    "ImageNet",
    "Imagen",
    "Inception module",
    "John Searle Chinese Room",
    "KV cache",
    "KV cache compression",
    "Kaplan scaling laws",
    "Kasparov AI",
    "LeNet",
    "LSTM",
    "Lisp machines",
    "Lookahead decoding",
    "Loihi chip",
    "MCP",
    "MQA",
    "MYCIN",
    "McCarthy AI",
    "Marvin Minsky society of mind",
    "Medusa heads",
    "Minsky perceptron",
    "Neuralink",
    "PagedAttention",
    "PEFT",
    "Pearl Bayesian",
    "Physical Intelligence",
    "QLoRA",
    "Q-learning",
    "RAG",
    "RLHF",
    "RNN",
    "ResNet skip connections",
    "Ring Attention",
    "RoBERTa",
    "Rumelhart backprop",
    "SB 1047",
    "SLM",
    "SHRDLU",
    "Sora",
    "Sutton and Barto",
    "Switch Transformer",
    "VAEs",
    "VGG net",
    "VLM",
    "Vaswani transformer",
    "adapter tuning",
    "agentic AI",
    "backpropagation",
    "batch normalization",
    "biological computing",
    "blocks world",
    "brain-computer interface",
    "chain-of-thought",
    "chain-of-thought scaling",
    "Chinese Room argument",
    "Chinchilla optimal",
    "circuit analysis",
    "compute governance",
    "constitutional AI",
    "convolutional neural network",
    "CNN history",
    "debate AI safety",
    "deep learning revolution",
    "diffusion models",
    "dropout regularization",
    "embodied AI",
    "encoder decoder transformer",
    "evolutionary computation",
    "existential risk AI",
    "expert systems",
    "feature visualization",
    "few-shot learning",
    "fine-tuning",
    "frame problem",
    "function calling",
    "fuzzy logic",
    "genetic algorithms",
    "humanoid robot AI",
    "in-context learning",
    "inference-time scaling",
    "infinite context",
    "instruction tuning",
    "intelligence explosion",
    "knowledge distillation",
    "latent diffusion",
    "long context",
    "LoRA",
    "mechanistic interpretability",
    "mixture of experts",
    "model context protocol",
    "model merging",
    "model souping",
    "MoE architecture",
    "multimodal AI",
    "neuro-symbolic AI",
    "neuromorphic computing",
    "neural networks history",
    "o1 reasoning",
    "post-AGI economy",
    "quantum advantage AI",
    "quantum machine learning",
    "reasoning models",
    "recurrent neural network",
    "recursive self-improvement",
    "reinforcement learning",
    "retrieval augmented generation",
    "robotics foundation model",
    "SVM",
    "SB 1047",
    "scalable oversight",
    "scaling laws",
    "second AI winter",
    "self-attention",
    "self-improvement AI",
    "self-play LLM",
    "sparse autoencoder",
    "speculative decoding",
    "speech language model",
    "stable diffusion",
    "superintelligence",
    "support vector machines",
    "symbolic AI",
    "synthetic data",
    "temporal difference learning",
    "test-time compute",
    "tool use LLM",
    "transformer architecture",
    "Turing Test",
    "Turing Test debate",
    "video generation",
    "vision language model",
    "weak-to-strong generalization",
    "word2vec",
    "world models",
    "x-risk AI",
    "Cyc project",
    "CoT prompting",
    "Lee Sedol",
    "machine sentience",
    "perceptron",
    "perceptron limitations",
]))

# Class H handles — tiered by query frequency
CLASS_H_HANDLES = {
    "tier_1": [
        "@abacaj",
        "@awnihannun",
        "@charles_irl",
        "@clattner_llvm",
        "@ggerganov",
        "@hwchase17",
        "@jerryjliu0",
        "@jxmnop",
        "@karpathy",
        "@rasbt",
        "@reach_vb",
        "@soumithchintala",
        "@StasBekman",
        "@swyx",
        "@vipulved",
    ],
    "tier_2": [
        "@AravSrinivas",
        "@AnthropicAI",
        "@ID_AA_Carmack",
        "@OpenAIDevs",
        "@amasad",
        "@drjimfan",
        "@levelsio",
        "@mckaywrigley",
        "@osanseviero",
        "@rauchg",
        "@sama",
        "@virattt",
        "@ylecun",
    ],
    "tier_3": [
        "@SarvamAI",
        "@ai4bharat",
        "@bhutanisanyam1",
        "@vivek_raghavan",
    ],
}

# ---------------------------------------------------------------------------
# Chunking logic
# ---------------------------------------------------------------------------

STANDARD_FILTER = " min_faves:1 -is:retweet -is:reply -is:nullcast lang:en"
LANGUAGE_FILTER = " min_faves:1 -is:retweet -is:reply -is:nullcast"

SAFETY_BUFFER = 10


def build_queries(keywords: list[str], filter_suffix: str) -> list[str]:
    """Chunk keywords into Twitter search queries respecting ≤500 char limit."""
    max_body = 500 - len(filter_suffix) - 2 - SAFETY_BUFFER  # 2 for parentheses

    queries: list[str] = []
    chunk: list[str] = []
    chunk_len = 0

    for kw in sorted(set(keywords)):
        quoted = f'"{kw}"'
        # Length contribution: quoted kw + " OR " separator (except first)
        addition = len(quoted) + (4 if chunk else 0)  # 4 = len(" OR ")

        if chunk and chunk_len + addition > max_body:
            queries.append("(" + " OR ".join(chunk) + ")" + filter_suffix)
            chunk = [quoted]
            chunk_len = len(quoted)
        else:
            if chunk:
                chunk_len += 4
            chunk.append(quoted)
            chunk_len += len(quoted)

    if chunk:
        queries.append("(" + " OR ".join(chunk) + ")" + filter_suffix)

    return queries


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    classes: dict[str, dict] = {
        "A": {
            "name": "Macro AI Models & Inference Frontier",
            "priority": "STANDARD",
            "keywords": CLASS_A_KEYWORDS,
            "filter": STANDARD_FILTER,
        },
        "B": {
            "name": "Orchestration & Agent Framework Bottlenecks",
            "priority": "STANDARD",
            "keywords": CLASS_B_KEYWORDS,
            "filter": STANDARD_FILTER,
        },
        "C": {
            "name": "Voice AI Stack — Latency, Reliability & UX",
            "priority": "STANDARD",
            "keywords": CLASS_C_KEYWORDS,
            "filter": STANDARD_FILTER,
        },
        "D": {
            "name": "Unit Economics & Margin Pain",
            "priority": "STANDARD",
            "keywords": CLASS_D_KEYWORDS,
            "filter": STANDARD_FILTER,
        },
        "E": {
            "name": "Language Moat — Regional, Dialect & Code-Switching",
            "priority": "STANDARD",
            "keywords": CLASS_E_KEYWORDS,
            "filter": LANGUAGE_FILTER,
        },
        "F": {
            "name": "Vertical Integrators & Builder Intent",
            "priority": "STANDARD",
            "keywords": CLASS_F_KEYWORDS,
            "filter": STANDARD_FILTER,
        },
        "G": {
            "name": "AI Terminology — Foundational, Current & Forward-Looking",
            "priority": "LOW",
            "keywords": CLASS_G_KEYWORDS,
            "filter": STANDARD_FILTER,
        },
    }

    keyword_classes: dict[str, dict] = {}
    stats: list[str] = []

    for cls_id, cfg in classes.items():
        queries = build_queries(cfg["keywords"], cfg["filter"])
        keyword_classes[cls_id] = {
            "name": cfg["name"],
            "priority": cfg["priority"],
            "queries": queries,
        }
        kw_count = len(set(cfg["keywords"]))
        max_len = max(len(q) for q in queries)
        avg_kw = kw_count / len(queries) if queries else 0
        stats.append(
            f"Class {cls_id}: {kw_count} keywords -> {len(queries)} queries "
            f"(avg {avg_kw:.1f} kw/query, max {max_len} chars)"
        )
        assert max_len <= 500, f"Class {cls_id} has query exceeding 500 chars: {max_len}"

    lexicon = {
        "version": "3.1",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "Keyword_Classes": keyword_classes,
        "Tracked_Handles": CLASS_H_HANDLES,
    }

    out_path = REPO_ROOT / "config" / "genesis_lexicon.json"
    out_path.write_text(json.dumps(lexicon, indent=2, ensure_ascii=False), encoding="utf-8")

    total_kw = sum(len(set(c["keywords"])) for c in classes.values())
    total_q = sum(len(kc["queries"]) for kc in keyword_classes.values())
    print(f"\ngenesis_lexicon.json written to {out_path}")
    print(f"Total keywords: {total_kw} | Total queries: {total_q}\n")
    for s in stats:
        print(s)

    # Spot-check: print 2 random queries per class
    import random
    print("\n--- Spot check (2 queries per class) ---")
    for cls_id, kc in keyword_classes.items():
        sample = random.sample(kc["queries"], min(2, len(kc["queries"])))
        for q in sample:
            suffix = LANGUAGE_FILTER if cls_id == "E" else STANDARD_FILTER
            assert q.endswith(suffix), f"Class {cls_id} query missing correct suffix"
            print(f"[{cls_id}] {q[:120]}{'...' if len(q)>120 else ''}")
    print("\nAll assertions passed.")


if __name__ == "__main__":
    main()
